// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Place is the predicate function for place builders.
type Place func(*sql.Selector)

// Titlename is the predicate function for titlename builders.
type Titlename func(*sql.Selector)
