// Code generated by entc, DO NOT EDIT.

package employee

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTel holds the string denoting the tel field in the database.
	FieldTel = "tel"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldBirthdayDate holds the string denoting the birthdaydate field in the database.
	FieldBirthdayDate = "birthday_date"
	// FieldAttendTime holds the string denoting the attendtime field in the database.
	FieldAttendTime = "attend_time"
	// FieldFinishTime holds the string denoting the finishtime field in the database.
	FieldFinishTime = "finish_time"

	// EdgeDepartment holds the string denoting the department edge name in mutations.
	EdgeDepartment = "department"
	// EdgePlace holds the string denoting the place edge name in mutations.
	EdgePlace = "place"
	// EdgeTitlename holds the string denoting the titlename edge name in mutations.
	EdgeTitlename = "titlename"

	// Table holds the table name of the employee in the database.
	Table = "employees"
	// DepartmentTable is the table the holds the department relation/edge.
	DepartmentTable = "employees"
	// DepartmentInverseTable is the table name for the Department entity.
	// It exists in this package in order to avoid circular dependency with the "department" package.
	DepartmentInverseTable = "departments"
	// DepartmentColumn is the table column denoting the department relation/edge.
	DepartmentColumn = "department_employee"
	// PlaceTable is the table the holds the place relation/edge.
	PlaceTable = "employees"
	// PlaceInverseTable is the table name for the Place entity.
	// It exists in this package in order to avoid circular dependency with the "place" package.
	PlaceInverseTable = "places"
	// PlaceColumn is the table column denoting the place relation/edge.
	PlaceColumn = "place_employee"
	// TitlenameTable is the table the holds the titlename relation/edge.
	TitlenameTable = "employees"
	// TitlenameInverseTable is the table name for the Titlename entity.
	// It exists in this package in order to avoid circular dependency with the "titlename" package.
	TitlenameInverseTable = "titlenames"
	// TitlenameColumn is the table column denoting the titlename relation/edge.
	TitlenameColumn = "titlename_employee"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldName,
	FieldTel,
	FieldEmail,
	FieldBirthdayDate,
	FieldAttendTime,
	FieldFinishTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Employee type.
var ForeignKeys = []string{
	"department_employee",
	"place_employee",
	"titlename_employee",
}
