// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/B6001186/app/ent/department"
	"github.com/B6001186/app/ent/employee"
	"github.com/B6001186/app/ent/place"
	"github.com/B6001186/app/ent/predicate"
	"github.com/B6001186/app/ent/titlename"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks      []Hook
	mutation   *EmployeeMutation
	predicates []predicate.Employee
}

// Where adds a new predicate for the builder.
func (eu *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	eu.predicates = append(eu.predicates, ps...)
	return eu
}

// SetUserID sets the User_id field.
func (eu *EmployeeUpdate) SetUserID(s string) *EmployeeUpdate {
	eu.mutation.SetUserID(s)
	return eu
}

// SetName sets the Name field.
func (eu *EmployeeUpdate) SetName(s string) *EmployeeUpdate {
	eu.mutation.SetName(s)
	return eu
}

// SetTel sets the Tel field.
func (eu *EmployeeUpdate) SetTel(s string) *EmployeeUpdate {
	eu.mutation.SetTel(s)
	return eu
}

// SetEmail sets the Email field.
func (eu *EmployeeUpdate) SetEmail(s string) *EmployeeUpdate {
	eu.mutation.SetEmail(s)
	return eu
}

// SetBirthdayDate sets the BirthdayDate field.
func (eu *EmployeeUpdate) SetBirthdayDate(t time.Time) *EmployeeUpdate {
	eu.mutation.SetBirthdayDate(t)
	return eu
}

// SetAttendTime sets the AttendTime field.
func (eu *EmployeeUpdate) SetAttendTime(t time.Time) *EmployeeUpdate {
	eu.mutation.SetAttendTime(t)
	return eu
}

// SetFinishTime sets the FinishTime field.
func (eu *EmployeeUpdate) SetFinishTime(t time.Time) *EmployeeUpdate {
	eu.mutation.SetFinishTime(t)
	return eu
}

// SetDepartmentID sets the department edge to Department by id.
func (eu *EmployeeUpdate) SetDepartmentID(id int) *EmployeeUpdate {
	eu.mutation.SetDepartmentID(id)
	return eu
}

// SetNillableDepartmentID sets the department edge to Department by id if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableDepartmentID(id *int) *EmployeeUpdate {
	if id != nil {
		eu = eu.SetDepartmentID(*id)
	}
	return eu
}

// SetDepartment sets the department edge to Department.
func (eu *EmployeeUpdate) SetDepartment(d *Department) *EmployeeUpdate {
	return eu.SetDepartmentID(d.ID)
}

// SetPlaceID sets the place edge to Place by id.
func (eu *EmployeeUpdate) SetPlaceID(id int) *EmployeeUpdate {
	eu.mutation.SetPlaceID(id)
	return eu
}

// SetNillablePlaceID sets the place edge to Place by id if the given value is not nil.
func (eu *EmployeeUpdate) SetNillablePlaceID(id *int) *EmployeeUpdate {
	if id != nil {
		eu = eu.SetPlaceID(*id)
	}
	return eu
}

// SetPlace sets the place edge to Place.
func (eu *EmployeeUpdate) SetPlace(p *Place) *EmployeeUpdate {
	return eu.SetPlaceID(p.ID)
}

// SetTitlenameID sets the titlename edge to Titlename by id.
func (eu *EmployeeUpdate) SetTitlenameID(id int) *EmployeeUpdate {
	eu.mutation.SetTitlenameID(id)
	return eu
}

// SetNillableTitlenameID sets the titlename edge to Titlename by id if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableTitlenameID(id *int) *EmployeeUpdate {
	if id != nil {
		eu = eu.SetTitlenameID(*id)
	}
	return eu
}

// SetTitlename sets the titlename edge to Titlename.
func (eu *EmployeeUpdate) SetTitlename(t *Titlename) *EmployeeUpdate {
	return eu.SetTitlenameID(t.ID)
}

// Mutation returns the EmployeeMutation object of the builder.
func (eu *EmployeeUpdate) Mutation() *EmployeeMutation {
	return eu.mutation
}

// ClearDepartment clears the department edge to Department.
func (eu *EmployeeUpdate) ClearDepartment() *EmployeeUpdate {
	eu.mutation.ClearDepartment()
	return eu
}

// ClearPlace clears the place edge to Place.
func (eu *EmployeeUpdate) ClearPlace() *EmployeeUpdate {
	eu.mutation.ClearPlace()
	return eu
}

// ClearTitlename clears the titlename edge to Titlename.
func (eu *EmployeeUpdate) ClearTitlename() *EmployeeUpdate {
	eu.mutation.ClearTitlename()
	return eu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (eu *EmployeeUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EmployeeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *EmployeeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   employee.Table,
			Columns: employee.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employee.FieldID,
			},
		},
	}
	if ps := eu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldUserID,
		})
	}
	if value, ok := eu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldName,
		})
	}
	if value, ok := eu.mutation.Tel(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldTel,
		})
	}
	if value, ok := eu.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmail,
		})
	}
	if value, ok := eu.mutation.BirthdayDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldBirthdayDate,
		})
	}
	if value, ok := eu.mutation.AttendTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldAttendTime,
		})
	}
	if value, ok := eu.mutation.FinishTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldFinishTime,
		})
	}
	if eu.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.PlaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PlaceTable,
			Columns: []string{employee.PlaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.PlaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PlaceTable,
			Columns: []string{employee.PlaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.TitlenameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.TitlenameTable,
			Columns: []string{employee.TitlenameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: titlename.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.TitlenameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.TitlenameTable,
			Columns: []string{employee.TitlenameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: titlename.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	hooks    []Hook
	mutation *EmployeeMutation
}

// SetUserID sets the User_id field.
func (euo *EmployeeUpdateOne) SetUserID(s string) *EmployeeUpdateOne {
	euo.mutation.SetUserID(s)
	return euo
}

// SetName sets the Name field.
func (euo *EmployeeUpdateOne) SetName(s string) *EmployeeUpdateOne {
	euo.mutation.SetName(s)
	return euo
}

// SetTel sets the Tel field.
func (euo *EmployeeUpdateOne) SetTel(s string) *EmployeeUpdateOne {
	euo.mutation.SetTel(s)
	return euo
}

// SetEmail sets the Email field.
func (euo *EmployeeUpdateOne) SetEmail(s string) *EmployeeUpdateOne {
	euo.mutation.SetEmail(s)
	return euo
}

// SetBirthdayDate sets the BirthdayDate field.
func (euo *EmployeeUpdateOne) SetBirthdayDate(t time.Time) *EmployeeUpdateOne {
	euo.mutation.SetBirthdayDate(t)
	return euo
}

// SetAttendTime sets the AttendTime field.
func (euo *EmployeeUpdateOne) SetAttendTime(t time.Time) *EmployeeUpdateOne {
	euo.mutation.SetAttendTime(t)
	return euo
}

// SetFinishTime sets the FinishTime field.
func (euo *EmployeeUpdateOne) SetFinishTime(t time.Time) *EmployeeUpdateOne {
	euo.mutation.SetFinishTime(t)
	return euo
}

// SetDepartmentID sets the department edge to Department by id.
func (euo *EmployeeUpdateOne) SetDepartmentID(id int) *EmployeeUpdateOne {
	euo.mutation.SetDepartmentID(id)
	return euo
}

// SetNillableDepartmentID sets the department edge to Department by id if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableDepartmentID(id *int) *EmployeeUpdateOne {
	if id != nil {
		euo = euo.SetDepartmentID(*id)
	}
	return euo
}

// SetDepartment sets the department edge to Department.
func (euo *EmployeeUpdateOne) SetDepartment(d *Department) *EmployeeUpdateOne {
	return euo.SetDepartmentID(d.ID)
}

// SetPlaceID sets the place edge to Place by id.
func (euo *EmployeeUpdateOne) SetPlaceID(id int) *EmployeeUpdateOne {
	euo.mutation.SetPlaceID(id)
	return euo
}

// SetNillablePlaceID sets the place edge to Place by id if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillablePlaceID(id *int) *EmployeeUpdateOne {
	if id != nil {
		euo = euo.SetPlaceID(*id)
	}
	return euo
}

// SetPlace sets the place edge to Place.
func (euo *EmployeeUpdateOne) SetPlace(p *Place) *EmployeeUpdateOne {
	return euo.SetPlaceID(p.ID)
}

// SetTitlenameID sets the titlename edge to Titlename by id.
func (euo *EmployeeUpdateOne) SetTitlenameID(id int) *EmployeeUpdateOne {
	euo.mutation.SetTitlenameID(id)
	return euo
}

// SetNillableTitlenameID sets the titlename edge to Titlename by id if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableTitlenameID(id *int) *EmployeeUpdateOne {
	if id != nil {
		euo = euo.SetTitlenameID(*id)
	}
	return euo
}

// SetTitlename sets the titlename edge to Titlename.
func (euo *EmployeeUpdateOne) SetTitlename(t *Titlename) *EmployeeUpdateOne {
	return euo.SetTitlenameID(t.ID)
}

// Mutation returns the EmployeeMutation object of the builder.
func (euo *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return euo.mutation
}

// ClearDepartment clears the department edge to Department.
func (euo *EmployeeUpdateOne) ClearDepartment() *EmployeeUpdateOne {
	euo.mutation.ClearDepartment()
	return euo
}

// ClearPlace clears the place edge to Place.
func (euo *EmployeeUpdateOne) ClearPlace() *EmployeeUpdateOne {
	euo.mutation.ClearPlace()
	return euo
}

// ClearTitlename clears the titlename edge to Titlename.
func (euo *EmployeeUpdateOne) ClearTitlename() *EmployeeUpdateOne {
	euo.mutation.ClearTitlename()
	return euo
}

// Save executes the query and returns the updated entity.
func (euo *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {

	var (
		err  error
		node *Employee
	)
	if len(euo.hooks) == 0 {
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EmployeeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	e, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return e
}

// Exec executes the query on the entity.
func (euo *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *EmployeeUpdateOne) sqlSave(ctx context.Context) (e *Employee, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   employee.Table,
			Columns: employee.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employee.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Employee.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := euo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldUserID,
		})
	}
	if value, ok := euo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldName,
		})
	}
	if value, ok := euo.mutation.Tel(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldTel,
		})
	}
	if value, ok := euo.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmail,
		})
	}
	if value, ok := euo.mutation.BirthdayDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldBirthdayDate,
		})
	}
	if value, ok := euo.mutation.AttendTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldAttendTime,
		})
	}
	if value, ok := euo.mutation.FinishTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldFinishTime,
		})
	}
	if euo.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.PlaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PlaceTable,
			Columns: []string{employee.PlaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.PlaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PlaceTable,
			Columns: []string{employee.PlaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.TitlenameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.TitlenameTable,
			Columns: []string{employee.TitlenameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: titlename.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.TitlenameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.TitlenameTable,
			Columns: []string{employee.TitlenameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: titlename.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	e = &Employee{config: euo.config}
	_spec.Assign = e.assignValues
	_spec.ScanValues = e.scanValues()
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return e, nil
}
