// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/B6001186/app/ent/department"
	"github.com/B6001186/app/ent/employee"
	"github.com/B6001186/app/ent/place"
	"github.com/B6001186/app/ent/titlename"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// EmployeeCreate is the builder for creating a Employee entity.
type EmployeeCreate struct {
	config
	mutation *EmployeeMutation
	hooks    []Hook
}

// SetUserID sets the User_id field.
func (ec *EmployeeCreate) SetUserID(s string) *EmployeeCreate {
	ec.mutation.SetUserID(s)
	return ec
}

// SetName sets the Name field.
func (ec *EmployeeCreate) SetName(s string) *EmployeeCreate {
	ec.mutation.SetName(s)
	return ec
}

// SetTel sets the Tel field.
func (ec *EmployeeCreate) SetTel(s string) *EmployeeCreate {
	ec.mutation.SetTel(s)
	return ec
}

// SetEmail sets the Email field.
func (ec *EmployeeCreate) SetEmail(s string) *EmployeeCreate {
	ec.mutation.SetEmail(s)
	return ec
}

// SetBirthdayDate sets the BirthdayDate field.
func (ec *EmployeeCreate) SetBirthdayDate(t time.Time) *EmployeeCreate {
	ec.mutation.SetBirthdayDate(t)
	return ec
}

// SetAttendTime sets the AttendTime field.
func (ec *EmployeeCreate) SetAttendTime(t time.Time) *EmployeeCreate {
	ec.mutation.SetAttendTime(t)
	return ec
}

// SetFinishTime sets the FinishTime field.
func (ec *EmployeeCreate) SetFinishTime(t time.Time) *EmployeeCreate {
	ec.mutation.SetFinishTime(t)
	return ec
}

// SetDepartmentID sets the department edge to Department by id.
func (ec *EmployeeCreate) SetDepartmentID(id int) *EmployeeCreate {
	ec.mutation.SetDepartmentID(id)
	return ec
}

// SetNillableDepartmentID sets the department edge to Department by id if the given value is not nil.
func (ec *EmployeeCreate) SetNillableDepartmentID(id *int) *EmployeeCreate {
	if id != nil {
		ec = ec.SetDepartmentID(*id)
	}
	return ec
}

// SetDepartment sets the department edge to Department.
func (ec *EmployeeCreate) SetDepartment(d *Department) *EmployeeCreate {
	return ec.SetDepartmentID(d.ID)
}

// SetPlaceID sets the place edge to Place by id.
func (ec *EmployeeCreate) SetPlaceID(id int) *EmployeeCreate {
	ec.mutation.SetPlaceID(id)
	return ec
}

// SetNillablePlaceID sets the place edge to Place by id if the given value is not nil.
func (ec *EmployeeCreate) SetNillablePlaceID(id *int) *EmployeeCreate {
	if id != nil {
		ec = ec.SetPlaceID(*id)
	}
	return ec
}

// SetPlace sets the place edge to Place.
func (ec *EmployeeCreate) SetPlace(p *Place) *EmployeeCreate {
	return ec.SetPlaceID(p.ID)
}

// SetTitlenameID sets the titlename edge to Titlename by id.
func (ec *EmployeeCreate) SetTitlenameID(id int) *EmployeeCreate {
	ec.mutation.SetTitlenameID(id)
	return ec
}

// SetNillableTitlenameID sets the titlename edge to Titlename by id if the given value is not nil.
func (ec *EmployeeCreate) SetNillableTitlenameID(id *int) *EmployeeCreate {
	if id != nil {
		ec = ec.SetTitlenameID(*id)
	}
	return ec
}

// SetTitlename sets the titlename edge to Titlename.
func (ec *EmployeeCreate) SetTitlename(t *Titlename) *EmployeeCreate {
	return ec.SetTitlenameID(t.ID)
}

// Mutation returns the EmployeeMutation object of the builder.
func (ec *EmployeeCreate) Mutation() *EmployeeMutation {
	return ec.mutation
}

// Save creates the Employee in the database.
func (ec *EmployeeCreate) Save(ctx context.Context) (*Employee, error) {
	if _, ok := ec.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "User_id", err: errors.New("ent: missing required field \"User_id\"")}
	}
	if _, ok := ec.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "Name", err: errors.New("ent: missing required field \"Name\"")}
	}
	if _, ok := ec.mutation.Tel(); !ok {
		return nil, &ValidationError{Name: "Tel", err: errors.New("ent: missing required field \"Tel\"")}
	}
	if _, ok := ec.mutation.Email(); !ok {
		return nil, &ValidationError{Name: "Email", err: errors.New("ent: missing required field \"Email\"")}
	}
	if _, ok := ec.mutation.BirthdayDate(); !ok {
		return nil, &ValidationError{Name: "BirthdayDate", err: errors.New("ent: missing required field \"BirthdayDate\"")}
	}
	if _, ok := ec.mutation.AttendTime(); !ok {
		return nil, &ValidationError{Name: "AttendTime", err: errors.New("ent: missing required field \"AttendTime\"")}
	}
	if _, ok := ec.mutation.FinishTime(); !ok {
		return nil, &ValidationError{Name: "FinishTime", err: errors.New("ent: missing required field \"FinishTime\"")}
	}
	var (
		err  error
		node *Employee
	)
	if len(ec.hooks) == 0 {
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EmployeeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ec.mutation = mutation
			node, err = ec.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			mut = ec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EmployeeCreate) SaveX(ctx context.Context) *Employee {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ec *EmployeeCreate) sqlSave(ctx context.Context) (*Employee, error) {
	e, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	e.ID = int(id)
	return e, nil
}

func (ec *EmployeeCreate) createSpec() (*Employee, *sqlgraph.CreateSpec) {
	var (
		e     = &Employee{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: employee.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employee.FieldID,
			},
		}
	)
	if value, ok := ec.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldUserID,
		})
		e.UserID = value
	}
	if value, ok := ec.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldName,
		})
		e.Name = value
	}
	if value, ok := ec.mutation.Tel(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldTel,
		})
		e.Tel = value
	}
	if value, ok := ec.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmail,
		})
		e.Email = value
	}
	if value, ok := ec.mutation.BirthdayDate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldBirthdayDate,
		})
		e.BirthdayDate = value
	}
	if value, ok := ec.mutation.AttendTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldAttendTime,
		})
		e.AttendTime = value
	}
	if value, ok := ec.mutation.FinishTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employee.FieldFinishTime,
		})
		e.FinishTime = value
	}
	if nodes := ec.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.PlaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PlaceTable,
			Columns: []string{employee.PlaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.TitlenameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.TitlenameTable,
			Columns: []string{employee.TitlenameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: titlename.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return e, _spec
}
