// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B6001186/app/ent/employee"
	"github.com/B6001186/app/ent/titlename"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// TitlenameCreate is the builder for creating a Titlename entity.
type TitlenameCreate struct {
	config
	mutation *TitlenameMutation
	hooks    []Hook
}

// SetName sets the Name field.
func (tc *TitlenameCreate) SetName(s string) *TitlenameCreate {
	tc.mutation.SetName(s)
	return tc
}

// AddEmployeeIDs adds the employee edge to Employee by ids.
func (tc *TitlenameCreate) AddEmployeeIDs(ids ...int) *TitlenameCreate {
	tc.mutation.AddEmployeeIDs(ids...)
	return tc
}

// AddEmployee adds the employee edges to Employee.
func (tc *TitlenameCreate) AddEmployee(e ...*Employee) *TitlenameCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return tc.AddEmployeeIDs(ids...)
}

// Mutation returns the TitlenameMutation object of the builder.
func (tc *TitlenameCreate) Mutation() *TitlenameMutation {
	return tc.mutation
}

// Save creates the Titlename in the database.
func (tc *TitlenameCreate) Save(ctx context.Context) (*Titlename, error) {
	if _, ok := tc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "Name", err: errors.New("ent: missing required field \"Name\"")}
	}
	var (
		err  error
		node *Titlename
	)
	if len(tc.hooks) == 0 {
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TitlenameMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tc.mutation = mutation
			node, err = tc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TitlenameCreate) SaveX(ctx context.Context) *Titlename {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tc *TitlenameCreate) sqlSave(ctx context.Context) (*Titlename, error) {
	t, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	t.ID = int(id)
	return t, nil
}

func (tc *TitlenameCreate) createSpec() (*Titlename, *sqlgraph.CreateSpec) {
	var (
		t     = &Titlename{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: titlename.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: titlename.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: titlename.FieldName,
		})
		t.Name = value
	}
	if nodes := tc.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   titlename.EmployeeTable,
			Columns: []string{titlename.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return t, _spec
}
