// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/B6001186/app/ent/titlename"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Titlename is the model entity for the Titlename schema.
type Titlename struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TitlenameQuery when eager-loading is set.
	Edges TitlenameEdges `json:"edges"`
}

// TitlenameEdges holds the relations/edges for other nodes in the graph.
type TitlenameEdges struct {
	// Employee holds the value of the employee edge.
	Employee []*Employee
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EmployeeOrErr returns the Employee value or an error if the edge
// was not loaded in eager-loading.
func (e TitlenameEdges) EmployeeOrErr() ([]*Employee, error) {
	if e.loadedTypes[0] {
		return e.Employee, nil
	}
	return nil, &NotLoadedError{edge: "employee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Titlename) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Titlename fields.
func (t *Titlename) assignValues(values ...interface{}) error {
	if m, n := len(values), len(titlename.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	t.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Name", values[0])
	} else if value.Valid {
		t.Name = value.String
	}
	return nil
}

// QueryEmployee queries the employee edge of the Titlename.
func (t *Titlename) QueryEmployee() *EmployeeQuery {
	return (&TitlenameClient{config: t.config}).QueryEmployee(t)
}

// Update returns a builder for updating this Titlename.
// Note that, you need to call Titlename.Unwrap() before calling this method, if this Titlename
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Titlename) Update() *TitlenameUpdateOne {
	return (&TitlenameClient{config: t.config}).UpdateOne(t)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (t *Titlename) Unwrap() *Titlename {
	tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Titlename is not a transactional entity")
	}
	t.config.driver = tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Titlename) String() string {
	var builder strings.Builder
	builder.WriteString("Titlename(")
	builder.WriteString(fmt.Sprintf("id=%v", t.ID))
	builder.WriteString(", Name=")
	builder.WriteString(t.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Titlenames is a parsable slice of Titlename.
type Titlenames []*Titlename

func (t Titlenames) config(cfg config) {
	for _i := range t {
		t[_i].config = cfg
	}
}
