// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DepartmentsColumns holds the columns for the "departments" table.
	DepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// DepartmentsTable holds the schema information for the "departments" table.
	DepartmentsTable = &schema.Table{
		Name:        "departments",
		Columns:     DepartmentsColumns,
		PrimaryKey:  []*schema.Column{DepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "tel", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "birthday_date", Type: field.TypeTime},
		{Name: "attend_time", Type: field.TypeTime},
		{Name: "finish_time", Type: field.TypeTime},
		{Name: "department_employee", Type: field.TypeInt, Nullable: true},
		{Name: "place_employee", Type: field.TypeInt, Nullable: true},
		{Name: "titlename_employee", Type: field.TypeInt, Nullable: true},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:       "employees",
		Columns:    EmployeesColumns,
		PrimaryKey: []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "employees_departments_employee",
				Columns: []*schema.Column{EmployeesColumns[8]},

				RefColumns: []*schema.Column{DepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "employees_places_employee",
				Columns: []*schema.Column{EmployeesColumns[9]},

				RefColumns: []*schema.Column{PlacesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "employees_titlenames_employee",
				Columns: []*schema.Column{EmployeesColumns[10]},

				RefColumns: []*schema.Column{TitlenamesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PlacesColumns holds the columns for the "places" table.
	PlacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// PlacesTable holds the schema information for the "places" table.
	PlacesTable = &schema.Table{
		Name:        "places",
		Columns:     PlacesColumns,
		PrimaryKey:  []*schema.Column{PlacesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// TitlenamesColumns holds the columns for the "titlenames" table.
	TitlenamesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// TitlenamesTable holds the schema information for the "titlenames" table.
	TitlenamesTable = &schema.Table{
		Name:        "titlenames",
		Columns:     TitlenamesColumns,
		PrimaryKey:  []*schema.Column{TitlenamesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DepartmentsTable,
		EmployeesTable,
		PlacesTable,
		TitlenamesTable,
	}
)

func init() {
	EmployeesTable.ForeignKeys[0].RefTable = DepartmentsTable
	EmployeesTable.ForeignKeys[1].RefTable = PlacesTable
	EmployeesTable.ForeignKeys[2].RefTable = TitlenamesTable
}
