/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEmployeeEdges,
    EntEmployeeEdgesFromJSON,
    EntEmployeeEdgesFromJSONTyped,
    EntEmployeeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntEmployee
 */
export interface EntEmployee {
    /**
     * AttendTime holds the value of the "AttendTime" field.
     * @type {string}
     * @memberof EntEmployee
     */
    attendTime?: string;
    /**
     * BirthdayDate holds the value of the "BirthdayDate" field.
     * @type {string}
     * @memberof EntEmployee
     */
    birthdayDate?: string;
    /**
     * Email holds the value of the "Email" field.
     * @type {string}
     * @memberof EntEmployee
     */
    email?: string;
    /**
     * FinishTime holds the value of the "FinishTime" field.
     * @type {string}
     * @memberof EntEmployee
     */
    finishTime?: string;
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntEmployee
     */
    name?: string;
    /**
     * Tel holds the value of the "Tel" field.
     * @type {string}
     * @memberof EntEmployee
     */
    tel?: string;
    /**
     * UserID holds the value of the "User_id" field.
     * @type {string}
     * @memberof EntEmployee
     */
    userId?: string;
    /**
     * 
     * @type {EntEmployeeEdges}
     * @memberof EntEmployee
     */
    edges?: EntEmployeeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntEmployee
     */
    id?: number;
}

export function EntEmployeeFromJSON(json: any): EntEmployee {
    return EntEmployeeFromJSONTyped(json, false);
}

export function EntEmployeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntEmployee {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attendTime': !exists(json, 'AttendTime') ? undefined : json['AttendTime'],
        'birthdayDate': !exists(json, 'BirthdayDate') ? undefined : json['BirthdayDate'],
        'email': !exists(json, 'Email') ? undefined : json['Email'],
        'finishTime': !exists(json, 'FinishTime') ? undefined : json['FinishTime'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'tel': !exists(json, 'Tel') ? undefined : json['Tel'],
        'userId': !exists(json, 'User_id') ? undefined : json['User_id'],
        'edges': !exists(json, 'edges') ? undefined : EntEmployeeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntEmployeeToJSON(value?: EntEmployee | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AttendTime': value.attendTime,
        'BirthdayDate': value.birthdayDate,
        'Email': value.email,
        'FinishTime': value.finishTime,
        'Name': value.name,
        'Tel': value.tel,
        'User_id': value.userId,
        'edges': EntEmployeeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


