/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntTitlenameEdges,
    EntTitlenameEdgesFromJSON,
    EntTitlenameEdgesFromJSONTyped,
    EntTitlenameEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTitlename
 */
export interface EntTitlename {
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntTitlename
     */
    name?: string;
    /**
     * 
     * @type {EntTitlenameEdges}
     * @memberof EntTitlename
     */
    edges?: EntTitlenameEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntTitlename
     */
    id?: number;
}

export function EntTitlenameFromJSON(json: any): EntTitlename {
    return EntTitlenameFromJSONTyped(json, false);
}

export function EntTitlenameFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTitlename {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'edges': !exists(json, 'edges') ? undefined : EntTitlenameEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntTitlenameToJSON(value?: EntTitlename | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'edges': EntTitlenameEdgesToJSON(value.edges),
        'id': value.id,
    };
}


